Add eligibility criteria to datasets.toml
asreview/synergy-dataset pull request #115
Opened 2024-12-02 18:02 UTC by J535D165

@Rensvandeschoot @EmilyWes extracted the eligibility criteria from the supplementing publication for each synergy dataset. This PR adds the quoted sections to the TOML metadata for the SYNERGY datasets. 

These sections are especially relevant to machine learning applications based on chatbot/LLM technology. For more use cases, please take a look at issue #94. 

In another PR, I will update the release pipeline and add the criteria to the released dataset (however, feel free to use it from the TOML file already).

2024-12-02 18:03 UTC, J535D165 commented on datasets.toml
> +_x0002_- Empirical studies (academic and industry) using large and small scale data sets AND.
hmmm. I think I will fix this by hand.

2024-12-02 18:08 UTC, J535D165 commented on datasets.toml
> +_x0002_- Studies comparing software metrics performance in the area of software fault prediction.
```suggestion
• Empirical studies (academic and industry) using large and small scale data sets AND.
• Studies comparing software metrics performance in the area of software fault prediction.
```

2024-12-03 14:36 UTC, EmilyWes requested changes
I think all criteria should start and end with a quote, resulting in triple quotes in the file. This to make clear they are blocked quotes from in the papers.
Currently this is not yet the case for: Appenzeller-Herzog, Bos, Brouwer, Donners, Leenaars_2020, Moran, Oud, Sep and Wassenaar.

2 criteria are missing (their names changed over time):
van_de_Schoot and (van_der_)Valk

2024-12-03 14:47 UTC, J535D165 commented
Good catch on Valk and Schoot dataset. Will open another PR.

2024-12-04 08:47 UTC, J535D165 commented on README.md
> +The SYNERGY dataset comprises the study selection of 26 systematic reviews. The dataset contains 169,288 records of which 2,834 records are manually labeled as inclusion by the authors of the systema
```suggestion
The SYNERGY dataset comprises the study selection of 26 systematic reviews. The dataset contains 169,288 records of which 2,834 records are manually labeled as inclusion by the authors of the systematic review. The eligibility criteria are added to the data as block quotations. 
```

2024-12-04 08:56 UTC, merged

2024-12-04 08:58 UTC, J535D165 commented
Thanks for the reviews. Helped.

@EmilyWes, I didn't incorporate your first suggestion because of the TOML specification https://toml.io/en/v1.0.0#string.